version: 2.1

orbs:
  python: circleci/python@2.1.1
  heroku: circleci/heroku@2.0.0

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - run:
          name: Run flake8
          command: python -m flake8
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  cont:
    docker:
      - image: cimg/go:1.17
        auth:
          username: jucgx
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
          TAG=$CIRCLE_SHA1
          docker build -t jucgx/oc-lettings-site:$TAG .
          docker build -t jucgx/oc-lettings-site:latest .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker push jucgx/oc-lettings-site:$TAG
          docker push jucgx/oc-lettings-site:latest
  
  deploy:
      executor: heroku/default
      environment:
        DJANGO_SETTINGS_MODULE: oc_lettings.settings.prod
      steps:
        - checkout
        - attach_workspace:
            at: ~/project
        - heroku/deploy-via-git
 

workflows:
  oc_lettings_site_pipeline:
    jobs:
      - build_and_test
      - cont:
          requires:
            - build_and_test
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - cont