version: 2.1

orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@0.0.10
  docker: circleci/docker@2.1.4

jobs:
  build_and_test: # this can be any name you choose
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  cont:
    docker:
      # replace with your preferred image
      - image: jcgx/oc-lettings-site:stable
    steps:
      - docker/push:
          image: test
  
  deploy: # this can be any name you choose
    executor: python/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git


workflows:
  test_my_app:
    jobs:
      - build_and_test
      - cont:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main
      - deploy:
          requires:
            - cont # only deploy if the build_and_test job has completed
          # filters:
          #   branches:
          #     only: main