version: 2.1

orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@0.0.10
  docker: circleci/docker@2.1.4

jobs:
  build_and_test:
    executor: python/default
    steps:
      # - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  cont:
    docker:
      # replace with your preferred image
      - image: python/default
        auth:
          username: jucgx
          password: $DOCKERHUB_PASSWORD
    steps:
      - attach_workspace:
          at: ~/project
      # - checkout
      # - setup_remote_docker:
      #     version: 20.10.14
      #     docker_layer_caching: true
      - run: |
          TAG=$CIRCLE_BUILD_NUM
          docker build -t jucgx/oc-lettings-site:$TAG .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker push jucgx/oc-lettings-site:$TAG
  
  deploy:
    executor: python/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git


workflows:
  test_my_app:
    jobs:
      - build_and_test
      - cont:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main
      - deploy:
          requires:
            - cont # only deploy if the build_and_test job has completed
          # filters:
          #   branches:
          #     only: main