version: 2.1

orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@0.0.10
  docker: circleci/docker@2.1.4

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  cont:
    docker:
      - image: cimg/go:1.17
        auth:
          username: jucgx
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
          TAG=$CIRCLE_SHA1
          docker build -t jucgx/oc-lettings-site:$TAG .
          docker build -t jucgx/oc-lettings-site:latest .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker push jucgx/oc-lettings-site:$TAG
          docker push jucgx/oc-lettings-site:latest
  
  deploy:
    executor: python/default
    environment:
      SENTRY_ORG: $SENTRY_ORG
      SENTRY_PROJECT: $SENTRY_PROJECT
      SENTRY_ENVIRONMENT: production
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true
      - run:
         name: Create release and notify Sentry of deploy
         command: |
           curl -sL https://sentry.io/get-cli/ | bash
           export SENTRY_LOG_LEVEL=debug
           export SENTRY_RELEASE=$(sentry-cli releases propose-version)
           sentry-cli --auth-token d6dc207329534e3495b40c81fc5ccee062c2638988d04df49faef2fab7e0ee1a  releases new -p oc_letting_site 2.7.0 --org cgx
           sentry-cli releases set-commits 2.7.0 --auto --auth-token d6dc207329534e3495b40c81fc5ccee062c2638988d04df49faef2fab7e0ee1a -p oc_letting_site --org cgx
           sentry-cli releases files 2.7.0 upload-sourcemaps path-to-sourcemaps-if-applicable --auth-token d6dc207329534e3495b40c81fc5ccee062c2638988d04df49faef2fab7e0ee1a -p oc_letting_site --org cgx
           sentry-cli releases finalize 2.7.0 --auth-token d6dc207329534e3495b40c81fc5ccee062c2638988d04df49faef2fab7e0ee1a -p oc_letting_site --org cgx
           sentry-cli releases deploys 2.7.0 new -e $SENTRY_ENVIRONMENT --auth-token d6dc207329534e3495b40c81fc5ccee062c2638988d04df49faef2fab7e0ee1a -p oc_letting_site --org cgx
  

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - cont:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main
      - deploy:
          requires:
            - cont # only deploy if the build_and_test job has completed
          # filters:
          #   branches:
          #     only: main